### ISSUE TITLE
Issue with light sensor[BUG]

### ISSUE THREAD

**Issue by vincentbraillard** [texx00/sandypi#60]
**Describe the bug**
after activation and desactivation of the light sensor, the brightness slider don't work anymore

**To Reproduce**
1: when starting the server with sensor off, the breathless slider work great between 0 to 100%
2: when turn on the sensor, the sensor work great also following the code
3: when turning off the sensor, the light cannot increase more than the last value when sensor was on (if 0, that 0 if a value, than this value)
4: the brightness slider work but from 0 to last value when sensor was on

**Screenshots**

**Platform (please complete the following information):**
all

**Comment by texx00** [comment]
Also this should be fixed in the latest alpha. The solution was to set the brightness at maximum when the sensor is switched off. Not the best solution probably but cannot do now. This is quite related to #59: when that one is done should be possible to keep the last brightness value instead of using the maximum
